server.port=8020
#Circuit Breaker
management.health.circuitbreakers.enabled=true
resilience4j.circuitbreaker.configs.default.registerHealthIndicator: true

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always

#Resilience Circuit Breaker
resilience4j.circuitbreaker.instances.Order-Service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.Order-Service.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.Order-Service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.Order-Service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.Order-Service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.Order-Service.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.Order-Service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.Order-Service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.Order-Service.slidingWindowType=COUNT_BASED
