server.port=8006

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always


resilience4j.circuitbreaker.instances.order-service.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.order-service.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.order-service.failureRateThreshold=50
resilience4j.circuitbreaker.instances.order-service.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.order-service.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.order-service.waitDurationInOpenState=6s
resilience4j.circuitbreaker.instances.order-service.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.order-service.slidingWindowSize=10
resilience4j.circuitbreaker.instances.order-service.slidingWindowType=COUNT_BASED

